# Atomic
# The goal of atomic is to eliminate context-switching and make atomic commits "almost" automatic.
# Only wrap commands you want local commits for. You can chain pre/post commands and reduce repetition
# by structuring everything declaratively in this config.

# Notes:
# - Atomic will run the first matching key it finds (snake_case or kebab-case both work).
# - Chaining supports raw shell commands or references to other [custom] blocks.
# - Hooks are optional: before / command / after.
# - You can still use '&&' or ';' for shell-side chaining if needed.

# Windows | Linux - shell chaining reference:
#   ';'  executes the next command regardless of success.
#   '&&' only runs next if previous succeeded.
#   '||' only runs next if previous failed.

# Examples:
#   mkdir rust_project; cd rust_project; cargo init
#   cargo build && cargo run
#   cargo build || cargo clippy


[custom.check]
command = "cargo check"

[custom.clippy]
before  = "echo Running Clippy"
command = "cargo clippy"
after   = "echo Clippy finished"

[custom.tw]
command = "cargo test --all-features --workspace"

[custom.clippy_max]
command = "cargo clippy --all-targets --all-features --workspace -- -D warnings"

[custom.doc]
command = "cargo doc --no-deps --document-private-items --all-features --workspace --open"

# Chain multiple commands, declared or raw
[custom.chain]
command = ["check", "tw", "cargo fmt"]

[plugin.generate-docs]
script = "./scripts/test"         # base path (no extension)
args = ["hello", "from", "Atomic!"] 
silent = true   # optional, defaults to false

[plugin.cleanup]
script = "./scripts/clean_temp.bat"