[package]
name = "cargo-atomic"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "4.5.4"
git2 = "0.18.3"
thiserror = "1.0.60"
toml = "0.8.12"
