[package]
name = "cargo-atomic"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "4.5.4"
config = "0.14.0"
git2 = "0.18.3"
notify = "6.1.1"
